hotkeys:
  shell:
    default:
      - - Ctrl-T
  toggle-window:
    - - Ctrl-Alt-C
  profile: {}
ssh:
  connections:
    - name: Bandwagonhost
      host: 69.171.71.245
      port: 29746
      user: root
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      group: null
      privateKey: 'C:\Users\yuans\.ssh\bwh'
    - name: Google Cloud Platform
      group: null
      host: 35.235.97.63
      port: 22
      user: yuanshenmick
      algorithms:
        hmac:
          - hmac-sha2-256
          - hmac-sha2-512
          - hmac-sha1
        kex:
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha1
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes256-gcm
          - aes256-gcm@openssh.com
        serverHostKey:
          - ssh-ed25519
          - ssh-rsa
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
      scripts: []
      privateKey: 'C:\Users\yuans\.ssh\gcp'
terminal:
  colorScheme:
    name: MaterialDark
    foreground: '#e5e5e5'
    background: '#232322'
    cursor: '#16afca'
    colors:
      - '#212121'
      - '#b7141f'
      - '#457b24'
      - '#f6981e'
      - '#134eb2'
      - '#560088'
      - '#0e717c'
      - '#efefef'
      - '#424242'
      - '#e83b3f'
      - '#7aba3a'
      - '#ffea2e'
      - '#54a4f3'
      - '#aa4dbc'
      - '#26bbd1'
      - '#d9d9d9'
  font: Cascadia Mono PL Regular
  ligatures: true
  cursorBlink: false
  environment: {}
  shell: powershell
  fontSize: 18
  profiles: []
  bracketedPaste: false
  autoOpen: false
  bell: visual
  profile: powershell
  customShell: pwsh
  background: colorScheme
  frontend: hterm
  recoverTabs: false
appearance:
  frame: thin
  vibrancy: true
  vibrancyType: fluent
  opacity: 0.92
  theme: Standard
enableAnalytics: false
enableWelcomeTab: false
enableAutomaticUpdates: false
